{
    "openapi": "3.0.0",
    "info": {
        "title": "StandupmMan API",
        "description": "OpenAPI Annotations for StandupMan API",
        "contact": {
            "name": "StandupMan Support",
            "url": "http://standupman.xyz",
            "email": "support@standupman.xyz"
        },
        "license": {
            "name": "MIT License",
            "url": "https://github.com/standupman/standupman/blob/master/LICENSE.md"
        },
        "version": "1.0.0"
    },
    "tags": [
        {
            "name": "Authentication",
            "description": "Authentication"
        },
        {
            "name": "Standup",
            "description": "Standup"
        },
        {
            "name": "Public",
            "description": "Public"
        },
        {
            "name": "User",
            "description": "User"
        }
    ],
    "basicAuth": {
        "name": "Authorization",
        "schema": {
            "type": "basic"
        }
    },
    "components": {
        "schemas": {
            "Standup": {
                "type": "object",
                "required": [
                    "name",
                    "completionTime",
                    "questions"
                ],
                "properties": {
                    "user_id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "completionTime": {
                        "type": "string"
                    },
                    "questions": {
                        "type": "object",
                        "properties": {
                            "question_x": {
                                "$ref": "#/components/schemas/StandupQuestion"
                            }
                        }
                    }
                }
            },
            "StandupQuestion": {
                "type": "object",
                "required": [
                    "title",
                    "response_type"
                ],
                "properties": {
                    "title": {
                        "type": "string"
                    },
                    "response_type": {
                        "type": "string"
                    }
                }
            },
            "StandupResponse": {
                "type": "object",
                "required": [
                    "standup_id",
                    "user_id",
                    "responseTime",
                    "answers"
                ],
                "properties": {
                    "standup_id": {
                        "type": "string"
                    },
                    "user_id": {
                        "type": "string"
                    },
                    "responseTime": {
                        "type": "string"
                    },
                    "answers": {
                        "type": "object",
                        "properties": {
                            "answer_x": {
                                "$ref": "#/components/schemas/StandupResponseAnswer"
                            }
                        }
                    }
                }
            },
            "StandupResponseAnswer": {
                "type": "object",
                "required": [
                    "question_id",
                    "response"
                ],
                "properties": {
                    "question_id": {
                        "type": "string"
                    },
                    "response": {
                        "type": "string"
                    }
                }
            },
            "User": {
                "type": "object",
                "required": [
                    "username",
                    "email",
                    "full_name",
                    "password"
                ],
                "properties": {
                    "configs": {
                        "type": "object"
                    },
                    "standups": {
                        "type": "array"
                    },
                    "username": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "full_name": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "Login": {
                "type": "object",
                "required": [
                    "username",
                    "password"
                ],
                "properties": {
                    "username": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "path": {
                        "type": "string"
                    }
                }
            }
        },
        "requestBodies": {
            "CreateStandupReq": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Standup"
                        },
                        "examples": {
                            "basic": {
                                "$ref": "#/components/examples/basic_standup_req"
                            }
                        }
                    }
                }
            },
            "UpdateStandupReq": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Standup"
                        },
                        "examples": {
                            "basic": {
                                "$ref": "#/components/examples/basic_standup_req"
                            }
                        }
                    }
                }
            },
            "CreateStandupResponseReq": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/StandupResponse"
                        },
                        "examples": {
                            "basic": {
                                "$ref": "#/components/examples/basic_standup_response_req"
                            }
                        }
                    }
                }
            },
            "StandupSubscriptionReq": {
                "content": {
                    "application/json": {
                        "schema": {},
                        "examples": {
                            "basic": {
                                "$ref": "#/components/examples/standup_subscription_req"
                            }
                        }
                    }
                }
            },
            "LoginReq": {
                "content": {
                    "application/json": {
                        "schema": {},
                        "examples": {
                            "basic": {
                                "value": {
                                    "username": "standupman",
                                    "password": "standupman"
                                }
                            }
                        }
                    }
                }
            }
        },
        "securitySchemes": {
            "basicAuth": {
                "type": "http",
                "scheme": "basic"
            }
        },
        "examples": {
            "basic_standup_req": {
                "value": {
                    "standup": {
                        "name": "Daily Standup Team 1",
                        "completionTime": "02/19/2022",
                        "questions": {
                            "question_1": {
                                "title": "What did you do today",
                                "response_type": "String"
                            },
                            "question_2": {
                                "title": "How many hours did you work today",
                                "response_type": "String"
                            },
                            "question_3": {
                                "title": "What will you work on till the next standup",
                                "response_type": "String"
                            }
                        }
                    }
                }
            },
            "basic_standup_res": {
                "value": {
                    "standup": {
                        "_id": "623b3979878b38d7c5bd6319",
                        "name": "Daily Standup Team 1",
                        "completionTime": "02/19/2022",
                        "questions": { 
                            "question_1": {
                                "title": "What did you do today",
                                "response_type": "String"
                            },
                            "question_2": {
                                "title": "How many hours did you work today",
                                "response_type": "String"
                            },
                            "question_3": {
                                "title": "What will you work on till the next standup",
                                "response_type": "String"
                            }
                        }
                    }
                }
            },
            "basic_standup_response_req": {
                "value": {
                    "standup_update": {
                        "standup_id": "62440d1b34b322b052e68c45",
                        "user_id": "624402f8407effaf82a5cc38",
                        "answers": {
                            "answer_1": {
                                "question_id": "question_1",
                                "response": "Troubleshoot faulty API endpoint at '/help/me'"
                            },
                            "answer_2": {
                                "question_id": "question_2",
                                "response": "I will be working to fix another broken endpoint"
                            }
                        }
                    }
                }
            },
            "basic_standup_response_res": {
                "value": {
                    "standUpUpdate": {
                        "_id": "627171efd474219153974c5c",
                        "standup_id": "62440d1b34b322b052e68c45",
                        "user_id": "624402f8407effaf82a5cc38",
                        "answers": {
                            "answer_1": {
                                "question_id": "question_1",
                                "response": "Troubleshoot faulty API endpoint at '/help/me'"
                            },
                            "answer_2": {
                                "question_id": "question_2",
                                "response": "I will be working to fix another broken endpoint"
                            }
                        },
                        "responseTime": "2022-05-03T18:18:23.818Z"
                    }
                }
            },
            "standup_subscription_req": {
                "value": {
                    "standup_id": "625fcba32291afeb6416dcf4"
                }
            },
            "standup_subscription_res": {
                "value": {
                    "success": true,
                    "user": {
                        "_id": "6260783cb0cd0d4e797c84d3",
                        "configs": {
                            "notification": {
                                "destination": "email"
                            }
                        },
                        "standups": [
                            "625fcba32291afeb6416dcf4"
                        ],
                        "username": "standupman",
                        "email": "standupman@gmail.com",
                        "full_name": "standupman",
                        "password": "$2b$10$O8Rkm5IIkXjyhD2QmUyp4Owl8ahTKfds5nQ4KvSMcCuboZ.oHcmWK"
                    }
                }
            },
            "standup_unsubscription_res": {
                "value": {
                    "success": true,
                    "user": {
                        "_id": "6260783cb0cd0d4e797c84d3",
                        "configs": {
                            "notification": {
                                "destination": "email"
                            }
                        },
                        "standups": [],
                        "username": "standupman",
                        "email": "standupman@gmail.com",
                        "full_name": "standupman",
                        "password": "$2b$10$O8Rkm5IIkXjyhD2QmUyp4Owl8ahTKfds5nQ4KvSMcCuboZ.oHcmWK"
                    }
                }
            }
        }
    },
    "paths": {
        "/": {
            "get": {
                "description": "Welcome to standupman api!",
                "tags": [
                    "Public"
                ],
                "responses": {
                    "200": {
                        "description": "Returns a mysterious string."
                    }
                }
            }
        },
        "/standups": {
            "get": {
                "description": "Get standups",
                "tags": [
                    "Standup"
                ],
                "responses": {
                    "200": {
                        "description": "Returns list of standups",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Standup"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/standups/new": {
            "post": {
                "description": "Create new standup",
                "tags": [
                    "Standup"
                ],
                "requestBody": {
                    "$ref": "#/components/requestBodies/CreateStandupReq"
                },
                "responses": {
                    "200": {
                        "description": "Returns newly created standup",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Standup"
                                },
                                "examples": {
                                    "basic": {
                                        "$ref": "#/components/examples/basic_standup_res"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/standups/{id}": {
            "delete": {
                "tags": [
                    "Standup"
                ],
                "description": "Deletes a standup",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the successful deleted standup",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Standup"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Standup"
                ],
                "description": "Updates a standup",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true
                    }
                ],
                "requestBody": {
                    "$ref": "#/components/requestBodies/UpdateStandupReq"
                },
                "responses": {
                    "200": {
                        "description": "Returns the successful updated standup",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Standup"
                                },
                                "examples": {
                                    "basic": {
                                        "$ref": "#/components/examples/basic_standup_res"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/standups/responses": {
            "get": {
                "description": "Get standup responses",
                "tags": [
                    "Standup"
                ],
                "responses": {
                    "200": {
                        "description": "Returns list of standup responses",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/StandupResponse"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/standups/complete": {
            "post": {
                "description": "Post standup notes",
                "tags": [
                    "Standup"
                ],
                "requestBody": {
                    "$ref": "#/components/requestBodies/CreateStandupResponseReq"
                },
                "responses": {
                    "200": {
                        "description": "Return the success confirmation of standup notes posted",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/StandupResponse"
                                },
                                "examples": {
                                    "basic": {
                                        "$ref": "#/components/examples/basic_standup_response_res"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/standups/subscribe": {
            "post": {
                "description": "Subscribe to a standup",
                "tags": [
                    "Standup"
                ],
                "requestBody": {
                    "$ref": "#/components/requestBodies/StandupSubscriptionReq"
                },
                "responses": {
                    "200": {
                        "description": "Return user with updated 'standups' field",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "basic": {
                                        "$ref": "#/components/examples/standup_subscription_res"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/standups/unsubscribe": {
            "post": {
                "description": "Unsubscribe to a standup",
                "tags": [
                    "Standup"
                ],
                "requestBody": {
                    "$ref": "#/components/requestBodies/StandupSubscriptionReq"
                },
                "responses": {
                    "200": {
                        "description": "Return user with updated 'standups' field",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "basic": {
                                        "$ref": "#/components/examples/standup_unsubscription_res"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get users",
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "Return the list users",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/User"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login User",
                "tags": [
                    "Authentication"
                ],
                "requestBody": {
                    "$ref": "#/components/requestBodies/LoginReq"
                },
                "responses": {
                    "200": {
                        "description": "Return a JWT token",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "basic": {
                                        "value": {
                                            "token": "xxx"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Register User",
                "tags": [
                    "Authentication"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Return a JWT token",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "basic": {
                                        "value": {
                                            "token": "xxx"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}